import pandas as pd
import os
import json
from groq import Groq
from dotenv import load_dotenv

# Load API Key
load_dotenv()
groq_api_key = os.getenv("GROQ_API_KEY", "")
client = Groq(api_key=groq_api_key) if groq_api_key else None

def rewrite_description_with_llm(sku, current_desc, tags):
    """Generates an improved listing copy addressing the pain points."""
    if not client:
        return current_desc + f"\n\n[MOCK AI EDIT: Address {', '.join(tags)} here. Add GROQ API Key for real improvements.]"
        
    try:
        prompt = f"""
        You are an expert e-commerce copywriter. The product currently has this description:
        "{current_desc}"
        
        However, customers are returning it and complaining about these issues: {', '.join(tags)}.
        
        Rewrite the product description to tackle these pain points directly, setting the right customer expectations while maintaining an elegant tone. Output ONLY the new description.
        """
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=200,
            temperature=0.7
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"LLM generation failed for {sku}: {e}")
        return current_desc

def train_priority_scorer(data_path="../../datasets", output_path="results"):
    print("Training Priority Scorer with AI Rewrite...")
    os.makedirs(output_path, exist_ok=True)
    
    returns = pd.read_csv(f"{data_path}/Returns.csv")
    costs = pd.read_csv(f"{data_path}/Return_costs.csv")
    products = pd.read_csv(f"{data_path}/Products.csv")
    
    # Attempt to load tags if generated by train_dashboard_nlp_tagger
    tags_file = f"{output_path}/top_return_reasons.json"
    tags_data = {}
    if os.path.exists(tags_file):
        with open(tags_file, "r") as f:
            tags_data = json.load(f)
            
    # Calculate Urgency
    merged = pd.merge(returns, costs, on="sku_id", how="left")
    merged['Total_return_cost'] = pd.to_numeric(merged['Total_return_cost'], errors='coerce').fillna(0)
    
    grouped = merged.groupby(['sku_id']).agg(
        velocity=('sku_id', 'count'),
        total_cost=('Total_return_cost', 'sum')
    ).reset_index()
    
    grouped['urgency_score'] = grouped['velocity'] * grouped['total_cost']
    grouped = grouped.sort_values(by='urgency_score', ascending=False)
    
    queue_cards = []
    
    # Process top 5 urgent items
    for _, row in grouped.head(5).iterrows():
        sku = row['sku_id']
        prod = products[products['sku_id'] == sku].iloc[0] if sku in products['sku_id'].values else None
        curr_desc = str(prod['description_text']) if prod is not None else "No description available."
        
        sku_tags = tags_data.get(sku, {}).get("pain_point_tags", [])
        
        # Simple dynamic action classifier
        action = "Review Quality"
        if any(t in " ".join(sku_tags).lower() for t in ["dark", "color", "light"]):
            action = "Fix photos"
        elif any(t in " ".join(sku_tags).lower() for t in ["size", "dimension", "fit"]):
            action = "Update dimensions"
            
        # Generative AI Rewrite Generation
        suggested_rewrite = None
        if action == "Update dimensions" or action == "Fix photos" or len(sku_tags) > 0:
            suggested_rewrite = rewrite_description_with_llm(sku, curr_desc, sku_tags)
            
        queue_cards.append({
            "sku_id": sku,
            "product_name": prod['product_name'] if prod is not None else "Unknown",
            "urgency_score": float(row['urgency_score']),
            "velocity": int(row['velocity']),
            "revenue_at_risk": float(row['total_cost']),
            "action": action,
            "pain_points": sku_tags,
            "original_description": curr_desc,
            "suggested_rewrite": suggested_rewrite
        })
        
    with open(f"{output_path}/priority_actions.json", "w") as f:
        json.dump(queue_cards, f, indent=4)
        
    print(f"Saved priority scorer queue to {output_path}/priority_actions.json")

if __name__ == "__main__":
    train_priority_scorer()
